package study.games.flashcard.wars.models.enums;

public enum PERMISSION {
    ADMIN_OPERATIONS,
    VIEW_ORGANIZATION,
    CREATE_ORGANIZATION,
    EDIT_ORGANIZATION,
    DELETE_ORGANIZATION,
    VIEW_GROUP,
    CREATE_GROUP,
    EDIT_GROUP,
    DELETE_GROUP,
    VIEW_STUDENT_PROFILES,
    CREATE_STUDENT_PROFILES,
    EDIT_STUDENT_PROFILES,
    DELETE_STUDENT_PROFILES,
    VIEW_FLASHCARD_QUESTIONS,
    CREATE_FLASHCARD_QUESTIONS,
    EDIT_FLASHCARD_QUESTIONS,
    DELETE_FLASHCARD_QUESTIONS,
    VIEW_FLASHCARD_GAME,
    CREATE_FLASHCARD_GAME,
    EDIT_FLASHCARD_GAME,
    DELETE_FLASHCARD_GAME,
    
}
