package com.games.flashcard.model.enums;

import java.util.Collection;

public enum PERMISSION {
    MANAGE_ORGANIZATION,
    MANAGE_ORGANIZATION_ADMINS,
    EDIT_ORGANIZATION_DETAILS,
    ADD_DELETE_TEACHER,
    ADD_DELETE_TEACHER_ASSISTANT,
    DELETE_STUDENT_ACCOUNT,
    ACCEPT_STUDENT_ACCESS_REQUEST,
    CREATE_FLASHCARD_SET,
    DELETE_FLASHCARD_SSET,
    CREATE_FLASHCARD,
    DELETE_FLASHCARD,
    START_STOP_GAME

}
